from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

from .common import UserMessage, to_jsonable, write_json


def _message_lines(messages: Sequence[UserMessage]) -> List[str]:
    lines: List[str] = []
    for msg in messages:
        label = "ERROR" if msg.level == "error" else "WARNING"
        line = f"- **{label} {msg.code}**: {msg.text}"
        if msg.suggestion:
            line += f"  \n  Suggestion: {msg.suggestion}"
        lines.append(line)
    return lines


def _result_lines(paths: Iterable[Path], output_dir: Path) -> List[str]:
    lines = []
    for path in paths:
        try:
            shown = path.relative_to(output_dir)
        except ValueError:
            shown = path
        lines.append(f"- `{shown}`")
    return lines


def write_reports(
    output_dir: Path,
    prepared: Any,
    diagnostics: Any,
    kalibr_summary: Any,
    target_yaml: Path,
    command_args: Dict[str, Any],
    messages: Sequence[UserMessage],
) -> None:
    data = {
        "target_yaml": str(target_yaml),
        "args": command_args,
        "prepared_dataset": to_jsonable(prepared),
        "diagnostics": to_jsonable(diagnostics),
        "kalibr": to_jsonable(kalibr_summary),
        "messages": to_jsonable(list(messages)),
    }
    write_json(output_dir / "calibration_report.json", data)

    lines: List[str] = [
        "# Calibration Report",
        "",
        "## Inputs",
        "",
        f"- Target: `{target_yaml}`",
        f"- Dataset: `{prepared.root}`",
        f"- Cameras: `{', '.join(prepared.camera_names)}`",
        f"- Target size: `{prepared.target_size[0]}x{prepared.target_size[1]}`",
        f"- Preprocess: `{prepared.preprocess}`",
        "",
        "## Messages",
        "",
    ]
    lines.extend(_message_lines(messages) or ["- No warnings or errors generated by the wrapper."])

    lines.extend([
        "",
        "## Diagnostics",
        "",
        f"- Target type: `{diagnostics.target_type}`",
        f"- Detector: `{diagnostics.detector}`",
        "",
    ])

    for cam in diagnostics.cameras:
        lines.extend([
            f"### {cam.camera}",
            "",
            f"- Images analyzed: `{cam.analyzed_count}/{cam.image_count}`",
            f"- Detection ratio: `{cam.detected_count}/{cam.analyzed_count}` (`{cam.detection_ratio:.2%}`)",
            f"- Image size: `{cam.image_size[0]}x{cam.image_size[1]}`",
            f"- Brightness / contrast / blur: `{cam.mean_brightness:.1f}` / `{cam.mean_contrast:.1f}` / `{cam.mean_blur_laplacian:.1f}`",
            f"- Corner coverage area ratio: `{cam.coverage_area_ratio:.2f}`",
            f"- 3x3 zone counts: `{cam.zone_counts}`",
            f"- Center std x/y: `{cam.center_std[0]:.3f}` / `{cam.center_std[1]:.3f}`",
            f"- Scale mean/std: `{cam.scale_mean:.3f}` / `{cam.scale_std:.3f}`",
            f"- Roll proxy std: `{cam.roll_std_deg:.1f} deg`",
            "",
        ])

    lines.extend([
        "## Kalibr",
        "",
    ])
    if kalibr_summary.calibration_result is None:
        lines.append("- Kalibr was skipped.")
    else:
        lines.append(f"- Return code: `{kalibr_summary.calibration_result.returncode}`")
        lines.append(f"- Log: `{kalibr_summary.calibration_result.log_path.name}`")
        if kalibr_summary.extracted_counts:
            lines.append(f"- Extracted counts: `{kalibr_summary.extracted_counts}`")
    lines.extend([
        "",
        "## Output Files",
        "",
    ])
    lines.extend(_result_lines(kalibr_summary.result_files, output_dir) or ["- No output files collected yet."])
    lines.append("")
    (output_dir / "calibration_report.md").write_text("\n".join(lines), encoding="utf-8")
