from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence

from .common import UserMessage, to_jsonable, write_json


def _message_lines(messages: Sequence[UserMessage]) -> List[str]:
    lines: List[str] = []
    for msg in messages:
        if msg.level == "error":
            label = "ERROR"
        elif msg.level == "warning":
            label = "WARNING"
        else:
            label = "INFO"
        line = f"- **{label} {msg.code}**: {msg.text}"
        if msg.suggestion:
            line += f"  \n  Suggestion: {msg.suggestion}"
        lines.append(line)
    return lines


def _result_lines(paths: Iterable[Path], output_dir: Path) -> List[str]:
    lines = []
    for path in paths:
        try:
            shown = path.relative_to(output_dir)
        except ValueError:
            shown = path
        lines.append(f"- `{shown}`")
    return lines


def _quality_lines(quality: Any, output_dir: Path) -> List[str]:
    if quality is None:
        return ["- No calibration-quality evaluation was generated."]
    lines: List[str] = [f"- Summary: `{quality.summary}`"]
    if getattr(quality, "parsed_files", None):
        shown_files = []
        for path in quality.parsed_files:
            try:
                shown_files.append(str(path.relative_to(output_dir)))
            except ValueError:
                shown_files.append(str(path))
        lines.append(f"- Parsed files: `{', '.join(shown_files)}`")
    if getattr(quality, "metrics", None):
        lines.append("")
        lines.append("| Metric | Value | Status | Detail |")
        lines.append("| --- | ---: | --- | --- |")
        for metric in quality.metrics:
            value = f"{metric.value:.4g} {metric.unit}".strip()
            lines.append(f"| `{metric.name}` | `{value}` | `{metric.status}` | {metric.detail or ''} |")
    else:
        lines.append("- No quality metrics were parsed.")
    return lines


def write_reports(
    output_dir: Path,
    prepared: Any,
    diagnostics: Any,
    kalibr_summary: Any,
    target_yaml: Path,
    command_args: Dict[str, Any],
    messages: Sequence[UserMessage],
    calibration_quality: Any = None,
) -> None:
    lang = str(command_args.get("lang", "zh"))
    data = {
        "target_yaml": str(target_yaml),
        "args": command_args,
        "prepared_dataset": to_jsonable(prepared),
        "diagnostics": to_jsonable(diagnostics),
        "kalibr": to_jsonable(kalibr_summary),
        "calibration_quality": to_jsonable(calibration_quality),
        "messages": to_jsonable(list(messages)),
    }
    write_json(output_dir / "calibration_report.json", data)

    lines: List[str] = [
        "# Calibration Report",
        "",
        "## Inputs",
        "",
        f"- Target: `{target_yaml}`",
        f"- Dataset: `{prepared.root}`",
        f"- Cameras: `{', '.join(prepared.camera_names)}`",
        f"- Target size: `{prepared.target_size[0]}x{prepared.target_size[1]}`",
        f"- Preprocess: `{prepared.preprocess}`",
        "",
        "## Messages",
        "",
    ]
    lines.extend(_message_lines(messages) or ["- No warnings or errors generated by the wrapper."])

    lines.extend([
        "",
        "## Diagnostics",
        "",
        f"- Target type: `{diagnostics.target_type}`",
        f"- Detector: `{diagnostics.detector}`",
        "",
    ])

    for cam in diagnostics.cameras:
        kalibr_counts = {}
        if getattr(kalibr_summary, "extracted_counts", None):
            kalibr_counts = kalibr_summary.extracted_counts.get(cam.camera, {})
        detector_mismatch = kalibr_counts.get("detected", 0) > 0 and cam.detected_count == 0
        lines.extend([
            f"### {cam.camera}",
            "",
            f"- Images analyzed: `{cam.analyzed_count}/{cam.image_count}`",
            f"- Detection ratio: `{cam.detected_count}/{cam.analyzed_count}` (`{cam.detection_ratio:.2%}`)",
        ])
        if kalibr_counts:
            lines.append(f"- Kalibr extracted: `{kalibr_counts.get('detected', 0)}/{kalibr_counts.get('total', 0)}`")
        if detector_mismatch:
            if lang == "zh":
                lines.append("- Coverage diagnostics: `包装器轻量检测器未复现 Kalibr 角点；角点是否可用以 Kalibr extracted 为准。`")
            else:
                lines.append("- Coverage diagnostics: `wrapper detector did not reproduce Kalibr corners; use Kalibr extracted counts for pass/fail.`")
        lines.extend([
            f"- Image size: `{cam.image_size[0]}x{cam.image_size[1]}`",
            f"- Brightness / contrast / blur: `{cam.mean_brightness:.1f}` / `{cam.mean_contrast:.1f}` / `{cam.mean_blur_laplacian:.1f}`",
        ])
        if detector_mismatch:
            if lang == "zh":
                lines.append("- Corner coverage metrics: `包装器轻量检测器不可用`")
            else:
                lines.append("- Corner coverage metrics: `not available from wrapper detector`")
        else:
            lines.extend([
                f"- Corner coverage area ratio: `{cam.coverage_area_ratio:.2f}`",
                f"- 3x3 zone counts: `{cam.zone_counts}`",
                f"- Center std x/y: `{cam.center_std[0]:.3f}` / `{cam.center_std[1]:.3f}`",
                f"- Scale mean/std: `{cam.scale_mean:.3f}` / `{cam.scale_std:.3f}`",
                f"- Roll proxy std: `{cam.roll_std_deg:.1f} deg`",
            ])
        lines.append("")

    lines.extend([
        "## Calibration Quality",
        "",
    ])
    lines.extend(_quality_lines(calibration_quality, output_dir))
    lines.extend([
        "",
        "## Kalibr",
        "",
    ])
    if kalibr_summary.calibration_result is None:
        lines.append("- Kalibr was skipped.")
    else:
        lines.append(f"- Return code: `{kalibr_summary.calibration_result.returncode}`")
        lines.append(f"- Log: `{kalibr_summary.calibration_result.log_path.name}`")
        if getattr(kalibr_summary, "fast_extraction", None):
            lines.append(f"- Fast extraction mode: `{kalibr_summary.fast_extraction}`")
            lines.append(f"- Fallback used: `{kalibr_summary.fallback_used}`")
            if getattr(kalibr_summary, "fallback_reason", ""):
                lines.append(f"- Fallback reason: `{kalibr_summary.fallback_reason}`")
        if getattr(kalibr_summary, "calibration_attempts", None):
            lines.append("- Attempts:")
            for idx, attempt in enumerate(kalibr_summary.calibration_attempts, start=1):
                lines.append(f"  - `{idx}` return `{attempt.returncode}`, log `{attempt.log_path.name}`")
        if kalibr_summary.extracted_counts:
            lines.append(f"- Extracted counts: `{kalibr_summary.extracted_counts}`")
    lines.extend([
        "",
        "## Output Files",
        "",
    ])
    lines.extend(_result_lines(kalibr_summary.result_files, output_dir) or ["- No output files collected yet."])
    lines.append("")
    (output_dir / "calibration_report.md").write_text("\n".join(lines), encoding="utf-8")


def write_cam_imu_report(
    output_dir: Path,
    target_yaml: Path,
    cam_chain: Path,
    imu_yaml: Path,
    command_args: Dict[str, Any],
    kalibr_result: Any,
    calibration_quality: Any,
    messages: Sequence[UserMessage],
    result_files: Sequence[Path],
) -> None:
    data = {
        "target_yaml": str(target_yaml),
        "cam_chain": str(cam_chain),
        "imu_yaml": str(imu_yaml),
        "args": command_args,
        "kalibr": to_jsonable(kalibr_result),
        "calibration_quality": to_jsonable(calibration_quality),
        "messages": to_jsonable(list(messages)),
        "result_files": to_jsonable(list(result_files)),
    }
    write_json(output_dir / "calibration_report.json", data)

    lines: List[str] = [
        "# Camera-IMU Calibration Report",
        "",
        "## Inputs",
        "",
        f"- Target: `{target_yaml}`",
        f"- Camera chain: `{cam_chain}`",
        f"- IMU YAML: `{imu_yaml}`",
        "",
        "## Messages",
        "",
    ]
    lines.extend(_message_lines(messages) or ["- No warnings or errors generated by the wrapper."])
    lines.extend([
        "",
        "## Calibration Quality",
        "",
    ])
    lines.extend(_quality_lines(calibration_quality, output_dir))
    lines.extend([
        "",
        "## Kalibr",
        "",
        f"- Return code: `{kalibr_result.returncode}`",
        f"- Log: `{kalibr_result.log_path.name}`",
        "",
        "## Output Files",
        "",
    ])
    lines.extend(_result_lines(result_files, output_dir) or ["- No output files collected yet."])
    lines.append("")
    (output_dir / "calibration_report.md").write_text("\n".join(lines), encoding="utf-8")
